### ISSUE TITLE
vsphere-csi-snapshotwebhook pods doesnt become available

### ISSUE THREAD

**Issue by ilpozzd** [vsphere-tmm/helm-charts#43]
vsphere-csi-snapshotwebhook pods doesnt become available with error:

```
MountVolume.SetUp failed for volume "webhook-certs" : secret "vsphere-csi-webhook-certs" not found
```

I found secret with `vsphere-csi-snapshot-webhook-certs` name. Is it mismatch?

Chart version: 2.1.1
Kubernetes version:  1.23.6

**Comment by ilpozzd** [comment]
#42 should fix this

**Comment by kfox1111** [comment]
This chart seems to have its own definitions for the webhook. But there is a semiofficial upstream chart for both the webhook and the controller. Would it be better to remove the existing webhook support instead of fixing it and then conditionally including the webhook and the controller?

Repo:
https://piraeus.io/helm-charts/

For example:
```
  chart: piraeus-charts/snapshot-controller
  version: 1.2.1
  chart: piraeus-charts/snapshot-validation-webhook
  version: 1.2.1
```

**Comment by kfox1111** [comment]
Actually, you can't turn it off without disabling snaphots entirely. This is problematic if you have non vmware drivers on the same cluster,

**Comment by kfox1111** [comment]
Should I open a new ticket for the issues I've raised here?
